CREATE DATABASE MFAS;
USE MFAS;
CREATE TABLE users (
    serial INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
);